spring.application.name=backend
server.port=${PORT:8081}
# MongoDB configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=ClusterDev

upstox.apiKey=${UPSTOX_API_KEY}
upstox.apiSecret=${UPSTOX_API_SECRET}
upstox.webhookUri= https://backendforautobot-production.up.railway.app/auth
logging.level.reactor.netty.http.client=DEBUG

spring.redis.host=localhost   # Redis later; leave like this
spring.redis.port=6379
upstox.accessToken=${UPSTOX_ACCESS_TOKEN}
# turn on DEBUG for your auth & feed services
logging.level.com.trader.backend.service.UpstoxAuthService=DEBUG
logging.level.com.trader.backend.service.LiveFeedService=DEBUG
logging.level.com.trader.backend.scheduler.NseJsonDownloader=DEBUG
# your Cloud-2 URL (include the ?1? if that's what your UI shows)
influx.url=https://us-east-1-1.aws.cloud2.influxdata.com

# the token you just generated in the UI (must have write scope on your bucket)
influx.token=${INFLUX_TOKEN}

# your organization name or ID (e.g. 'Johntradecorp')
influx.org=Johntradecorp

# the name of the bucket you created (e.g. 'Ticks')
influx.bucket=Ticks
logging.level.com.trader.backend.service.StreamController=DEBUG
logging.level.com.trader.backend.service.NseInstrumentService=DEBUG
spring.main.allow-bean-definition-overriding=true
