spring.application.name=backend
 server.port=${PORT:8081}
# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://imanuelsha:Johnwick007@clusterdev.nzpqse9.mongodb.net/?retryWrites=true&w=majority&ssl=true
spring.data.mongodb.database=ClusterDev

upstox.apiKey=97fde129-556b-4a84-9083-9fea5eb53fb0
upstox.apiSecret=ofye1h1t8e
upstox.webhookUri= https://backendforautobot-production.up.railway.app/auth
logging.level.reactor.netty.http.client=${REACTOR_NETTY_HTTP_CLIENT_LOG_LEVEL:INFO}

spring.redis.host=localhost   # Redis later; leave like this
spring.redis.port=6379
upstox.accessToken=eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyU0M3WjkiLCJqdGkiOiI2ODIwNDk1Yzg2M2M4ODY1MDAxOGE4MmQiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc0Njk0NjM5NiwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzQ3MDAwODAwfQ.mLgDAxc1M6o_w_gCzbYtQXGjXOcEmCce2qDqixa4BDc
# turn on DEBUG for your auth & feed services
logging.level.com.trader.backend.service.UpstoxAuthService=${UPSTOX_AUTH_LOG_LEVEL:INFO}
logging.level.com.trader.backend.service.LiveFeedService=${LIVEFEED_LOG_LEVEL:INFO}
logging.level.com.trader.backend.scheduler.NseJsonDownloader=${NSE_JSON_DOWNLOADER_LOG_LEVEL:INFO}
# your Cloud-2 URL (include the ?1? if that?s what your UI shows)
influx.url=https://us-east-1-1.aws.cloud2.influxdata.com

# the token you just generated in the UI (must have write scope on your bucket)
influx.token=wwwL6sNhLj8_C4k-n5nxndx2hTTwf_kZMFkqbvkBjohPp5_F4SKE6mlSEC-bco3sUreA70PExOhby-Pmfl_0yQ==

# your organization name or ID (e.g. ?Johntradecorp?)
influx.org=Johntradecorp

# the name of the bucket you created (e.g. ?Ticks?)
influx.bucket=Ticks
logging.level.com.trader.backend.service.StreamController=${STREAM_CONTROLLER_LOG_LEVEL:INFO}
logging.level.com.trader.backend.service.NseInstrumentService=${NSE_INSTRUMENT_LOG_LEVEL:INFO}
spring.main.allow-bean-definition-overriding=true
